set test "Programmatic traces"

proc compare_output {filename size policy} {
    global tool

    set test_output [exec cat input/trace.out | ./${tool} --num-pages $size --policy $policy]
    set good_output [exec cat input/trace.out | ./${tool}-good --num-pages $size --policy $policy]

    if {[string compare $test_output $good_output] == 0} {
	pass "$filename/$size/$policy"
    } else {
	fail "$filename/$size/$policy"
    }
}

global POLICY

foreach type {sequential loop random} {
    for {set i 1} {$i < 50} {incr i} {
	set max_pages [expr int(rand() * 1001)]
	set total_addresses [expr int(rand() * 1001)]
	system "./gen-trace --$type --max-pages $max_pages --total-addresses $total_addresses > input/trace.out"
	compare_output "input/trace.out" 1000 $POLICY
    }
}

system "rm input/trace.out"
